title: Jose Garcia
logo: /images/fotoperfil.jpg
description: Data Analyst, Machine Learning enthusiast and Petroleum Engineer
             
             <a>Contact</a>
             
             jgarciag@gwmail.gwu.edu
             
             <a href="https://www.linkedin.com/in/jlgarciajose/">LinkedIn</a>
             
             <a href="https://github.com/jgarcia2411">GitHub</a>
             
theme: jekyll-theme-minimal
