title: Jose Garcia
logo: /images/fotoperfil.jpg
description: Data Analyst, Machine Learning enthusiast and Petroleum Engineer
             **Contact** 
             jgarciag@gwmail.gwu.edu
             LinkedIn
theme: jekyll-theme-minimal
