title: Jose Garcia
logo: /images/fotoperfil2.jpg
description: >
             <strong>Data Analyst, Machine Learning Enthusiast and Petroleum Engineer</strong>
             <br><br>
             <a><strong>Contact</strong></a>
             <br><br>
              - garciaguerra.jl@gmail.com
             <br><br>
              - <a href="https://www.linkedin.com/in/jlgarciajose/">Find me on LinkedIn</a>
             <br><br>
              - <a href="https://github.com/jgarcia2411">Navigate to my GitHub</a>
             <br><br>
             <br><br>
             
theme: jekyll-theme-minimal
